name: Adjust Accuracy

on:
  schedule:
    - cron: "0 */3 * * *"  # every 3 hours
  workflow_dispatch:

jobs:
  adjust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run adjuster
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python accuracy_adjuster.py
      - name: Commit feeds.yaml if changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add feeds.yaml || true
          git commit -m "Auto-adjust feeds confidence" || echo "No change"
          git push || echo "Push failed"
