name: Predictoor Agent Auto-Runner

on:
  schedule:
    - cron: "*/30 * * * *"   # ⏱️ every 30 minutes
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - "feeds.yaml"          # 🔔 run instantly when feeds.yaml changes
      - ".github/workflows/predict.yml"

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Auto-update contract + relayer
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python contract_auto.py

      - name: Run agent predictions
        env:
          WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python agent_predictoor.py

      - name: Commit logs (performance & accuracy)
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add performance_log.json accuracy_log.json || true
          git commit -m "Auto: update logs" || echo "No changes to commit"
          git push
