name: Refresh Feeds

on:
  schedule:
    - cron: "0 */1 * * *"  # every 1 hour
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt requests python-telegram-bot

      - name: Refresh feeds
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python - <<'PYTHON_SCRIPT'
import os, json
from datetime import datetime
from telegram import Bot

with open("agent_instructions.json","r") as f:
    cfg = json.load(f)

FEEDS = cfg["feeds"]
bot = Bot(token=os.getenv(cfg["telegram"]["bot_token_env"]))
CHAT_ID = os.getenv(cfg["telegram"]["chat_id_env"])
performance_file = cfg["logging"]["performance_file"]

def notify(msg):
    print(msg)
    try:
        bot.send_message(chat_id=CHAT_ID, text=msg)
    except Exception as e:
        print(f"Telegram notify failed: {e}")

for feed in FEEDS:
    ts = datetime.utcnow().isoformat()
    notify(f"[{ts}] Feed refreshed: {feed}")
    with open(performance_file,"a") as f:
        f.write(f"{ts} - Refreshed feed: {feed}\n")

notify("✅ All feeds refreshed successfully.")
PYTHON_SCRIPT
