name: Refresh Feeds

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Refresh agent_instructions.json
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python - <<'EOF'
          import os, json, requests

          TASKADE_FEEDS_API = "https://api.taskade.com/v1/feeds"  # replace with actual feed source if needed
          AGENT_JSON = "agent_instructions.json"

          try:
              r = requests.get(TASKADE_FEEDS_API, timeout=10)
              r.raise_for_status()
              feeds = r.json().get("feeds", [])

              agent_config = {}
              if os.path.exists(AGENT_JSON):
                  with open(AGENT_JSON, "r") as f:
                      agent_config = json.load(f)

              agent_config["feeds"] = []
              for feed in feeds:
                  agent_config["feeds"].append({
                      "name": feed["name"],
                      "exchange": feed["exchange"],
                      "interval_minutes": feed.get("interval_minutes", 30)
                  })

              with open(AGENT_JSON, "w") as f:
                  json.dump(agent_config, f, indent=2)

              print(f"✅ agent_instructions.json updated with {len(feeds)} feeds.")

          except Exception as e:
              print(f"❌ Failed to refresh feeds: {e}")
          EOF
