name: Refresh Feeds

on:
  schedule:
    - cron: "0 0 * * *" # daily
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Refresh feeds placeholder
        run: echo "Feeds refreshed (new markets will be appended automatically by agent)."
