name: Test Telegram Connection

on:
  workflow_dispatch:

jobs:
  telegram_test:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MESSAGE="✅ Telegram connection successful! Your Predictoor agent is ready to run."
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
            -d chat_id=${TELEGRAM_CHAT_ID} \
            -d text="$MESSAGE"
